// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiiiqjkAFD0IYwUhUJANAvCe4TNbS2K-8',
    appId: '1:91519037272:web:01a16326f58b84cd0f3f2d',
    messagingSenderId: '91519037272',
    projectId: 'finalproject-35698',
    authDomain: 'finalproject-35698.firebaseapp.com',
    storageBucket: 'finalproject-35698.appspot.com',
    measurementId: 'G-EK8GWVE2ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ibiqMBncG1FfDHe9jcgnCzh4dcVHJFE',
    appId: '1:91519037272:android:63f479246beb51fa0f3f2d',
    messagingSenderId: '91519037272',
    projectId: 'finalproject-35698',
    storageBucket: 'finalproject-35698.appspot.com',
  );
}
